// app.vue

<script setup lang="ts">
import jsonData from './resume.json';
</script>

<template>
  <div class="gridboard">
    <div class="grid2 gridbox" :style="{ backgroundImage: 'url(\'/img/bg.png\')', backgroundPosition: 'center' }">
      <div :style="{ 
        display: 'grid', gridAutoRows: 'auto auto',
      }">
        <h3>Hi, My name is</h3>
        <h1 :style="{ marginTop: '0.1em' }">{{ jsonData.name }}</h1>
      </div>
    </div>
    <div class="grid1 gridbox">
       <ul v-for="role in jsonData.desp"">
        <p :style="{ marginBottom: '-1em' }">{{ role }}</p>
       </ul>  
    </div>
  </div>
  <div class="gridboard">
    <div class="gridbox grid1" :style="{ backgroundColor: '#145C9E' }">
       <h3>About me</h3>
       <br>
       <p>{{ jsonData.aboutMe[1] }}</p>
    </div>
    <div class="gridbox grid2" :style="{ backgroundColor: '#AF1B3F' }">
      <h3>My Skills</h3>
      <br>
      <p>{{ jsonData.aboutMe[0] }}</p>
      <br>
      <div v-for="skill in jsonData.skills" :style="{ padding: '18px' }">
        <h3>{{ skill.name }}</h3>
        <p>{{ skill.desp }}</p>
      </div>
    </div>
  </div>
  <div class="gridboard" :style="{ backgroundColor: '#20A4F3' }">
    <div class="gridbox grid1">
       <h3>Past Careers</h3>
    </div>
    <div class="grid2">
      <div v-for="work in jsonData.workExp">
        <div :style="{
          padding: '2em',
          margin: '1em',
          backgroundColor: '#2F3061',
          borderRadius: '12px'
        }">
          <p>{{ work.subtitle }}</p>
          <h3>{{ work.title }}</h3>
          <p>{{ work.descp }}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="gridboard">
    <div class="gridbox grid1">
       <h3>Contact</h3>
       <p>Ways to get touch with me</p>
    </div>
    <div class="grid2">
      <div :style="{
          padding: '2em',
          margin: '1em',
          backgroundColor: '#1b263b',
          borderRadius: '12px'
        }">
          <p>
            GitHub : <a href="https://github.com/"+{{ jsonData.contact.github }}>@{{ jsonData.contact.github }}</a>
          </p>
        </div>
        <div :style="{
          padding: '2em',
          margin: '1em',
          backgroundColor: '#1b263b',
          borderRadius: '12px'
        }">
          <p>
            E-mail : <a href="mailto:"+{{ jsonData.contact.email }}>{{ jsonData.contact.email }}</a>
          </p>
        </div>
        <div :style="{
          padding: '2em',
          margin: '1em',
          backgroundColor: '#1b263b',
          borderRadius: '12px'
        }">
          <p>
            LinkedIn : <a href={{ jsonData.contact.linkedin }}>{{ jsonData.contact.linkedin }}</a>
          </p>
        </div>
        <div :style="{
          padding: '2em',
          margin: '1em',
          backgroundColor: '#1b263b',
          borderRadius: '12px'
        }">
          <p>
            WhatsApp : <a href="https://wa.me/"+{{ jsonData.contact.whatsapp }}>@{{ jsonData.contact.whatsapp }}</a>
          </p>
        </div>
    </div>
  </div>
  <div id="panel">
    <p>Scroll down to look more</p>
  </div>
</template>

// src/App.tsx
import myRole from './states/roleState';
import resume from './assets/resume.json';
import logo from './assets/img/bg.png'
import { useEffect } from 'react';
import './App.css'

function App() {

  let ridx = myRole((state) => state.roleIdx);
  const updateRole = myRole((state) => state.updateRole);
  const roles = resume.desp;

  useEffect(() => {
    const cycler = setInterval(() => {
      updateRole(roles.length-1 <= ridx? 0 : ridx+1); 
    }, 500);
    return () => clearInterval(cycler); 
  });

  return (
    <>
      <div id='mainboard'>
        <div className='card'style={{ backgroundColor: '#EEC643', padding: '12px' }}>
          <code style={{ color: 'black' }}>hover over title to reveal</code>
          <div className='tab'>
            <h1>Skills</h1>
            {
              resume.skills.map(skill => (
                <div className='crumb'>
                  <div>
                    <h3>{skill.name}</h3>
                    <code>{skill.desp}</code>
                  </div>
                  <div>
                    <img src={skill.icon} alt="" style={{ scale: '0.5' }} />
                  </div>
                </div>
              ))
            }
          </div>
          <div className='tab'>
            <h1>Work Experiences</h1>
            <div style={{ padding: '6px' }}></div>
            {
              resume.workExp.map(work => (
                <div style={{ paddingTop: '20px' }}>                 
                  <h2>{work.title}</h2>
                  <br />
                  <code>
                    {work.subtitle}
                    <br />
                    {work.descp}
                  </code>
                </div>
              ))
            }
          </div> 
           <div className='tab'>
            <h1>Contact</h1>
            <div style={{ padding: '6px' }}></div>
            <code>GitHub : <a href={'https://github.com/'+resume.contact['github']}>{"@"+resume.contact['github']}</a></code>
            <br />
            <code>E-mail : <a href={'mailto'+resume.contact['email']}>{resume.contact['email']}</a></code>
            <br />
            <code>Whatsapp : <a href={'https://wa.me/'+resume.contact['whatsapp']}>{resume.contact['whatsapp']}</a></code>
            <br />
            <code>LinkedIn : <a href={resume.contact['linkedin']}>{resume.contact['linkedin']}</a></code>
            <br />
          </div> 
        </div>
        <div className='rowCard' style={{ width: '100%' }}>
          <div className='card' style={{ backgroundColor: '#0E79B2', padding: '18px' }}>
               <h2>About me</h2>
               {resume.aboutMe.map(txt => (<p>{txt}</p>))}
          </div>
          <div className='colCard' style={{ width: '100%'}}>
            <div className='card' style={{ backgroundColor: '#001F54', padding: '24px' }}>
              <p>Hi, My name is</p>
              <h1>{resume.name}</h1>
              <p>{roles[ridx]}</p>
            </div>
            <div className='card'>
              <img src={logo} alt="My photo" style={{ 
                objectFit: 'cover', 
                height: '100%', width: '100%', 
                padding: '-4em'
              }}/>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
